name: docker
on:
  push:
    branches:
      - develop_account_page
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context:  ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/backend-test:latest
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context:  ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/frontend-test:latest
