name: test.api
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  api
    steps:
      # checks-out git repo and access it
      - name: Checking out
        uses: actions/checkout@v3
      - name: Viewing folder structure after checks-out
        run: |
          echo viewing.....
          ls
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-node-
      - name: Building
        run: npm ci
      - name: building
        run: 
          npm run build
      - name: view folder
        run:  |
          echo viewing.....
          ls
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}