name: docker
on:
  push:
    branches:
      - develop_account_page
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      -
        name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          
          file: ./api/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/back-end-test:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MY_TOKEN }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          
          file: ./client/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/front-end-test:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MY_TOKEN }}
